describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://aprass.studio/')
    cy.get('.header__top__right > :nth-child(1) > a').click()
    cy.get('#username').type('dny')
    cy.get('#password').type('12345678')
    cy.get('#password').type('12345678')
    cy.get('#signinbtn').click()
    cy.get('.header__menu > ul > :nth-child(2) > a').click()
    cy.get('.header__nav__option > [href="https://aprass.studio/cart"] > .badge').click()
    cy.get('.primary-btn').click()
    cy.get('.checkout__order > .site-btn').click()
  })
})

//test case 2 (order dengan check boc COD)
describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://aprass.studio/')
    cy.get('.header__top__right > :nth-child(1) > a').click()
    cy.get('#username').type('dny')
    cy.get('#password').type('12345678')
    cy.get('#password').type('12345678')
    cy.get('#signinbtn').click()
    cy.get('.header__menu > ul > :nth-child(2) > a').click()
    cy.get('.header__nav__option > [href="https://aprass.studio/cart"] > .badge').click()
    cy.get('.primary-btn').click()
    cy.get('.checkmark').click()
    cy.get('.checkout__order > .site-btn').click()
  })
})

//test case 3 (order dengan check box COD dan mengisi order notes )
describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://aprass.studio/')
    cy.get('.header__top__right > :nth-child(1) > a').click()
    cy.get('#username').type('dny')
    cy.get('#password').type('12345678')
    cy.get('#password').type('12345678')
    cy.get('#signinbtn').click()
    cy.get('.header__menu > ul > :nth-child(2) > a').click()
    cy.get('.header__nav__option > [href="https://aprass.studio/cart"] > .badge').click()
    cy.get('.primary-btn').click()
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(4) > input').type('terserah')
    cy.get('.checkmark').click()
    cy.get('.checkout__order > .site-btn').click()
  })
})